# Generated by Django 3.1.3 on 2020-11-07 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allmovies',
            old_name='duration',
            new_name='Duration',
        ),
        migrations.RenameField(
            model_name='allmovies',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='allmovies',
            old_name='rating',
            new_name='Rating',
        ),
        migrations.AddField(
            model_name='allmovies',
            name='Type',
            field=models.CharField(default='action', max_length=100),
        ),
    ]
