# Generated by Django 3.1.3 on 2020-11-07 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20201107_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='allmovies',
            name='Year',
            field=models.IntegerField(default=2018),
        ),
    ]
